# Generated by Django 6.0.1 on 2026-01-28 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('apellido', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cochera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocheras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupado', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(blank=True, max_length=30)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='parking.cochera')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.tipoespacio')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=15, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parking.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.tipoespacio')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='parking.cochera')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.tipoespacio')),
            ],
            options={
                'unique_together': {('cochera', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], default='ABIERTO', max_length=10)),
                ('ingreso_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('egreso_at', models.DateTimeField(blank=True, null=True)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='parking.cochera')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='parking.espacio')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='parking.vehiculo')),
            ],
            options={
                'indexes': [models.Index(fields=['cochera', 'estado'], name='parking_mov_cochera_65fa55_idx'), models.Index(fields=['vehiculo', 'estado'], name='parking_mov_vehicul_f0e6d1_idx'), models.Index(fields=['espacio', 'estado'], name='parking_mov_espacio_887b3e_idx')],
            },
        ),
    ]
