# Generated by Django 6.0.1 on 2026-01-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='patente',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='patente_ult3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ticket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('ticket',), name='uq_vehiculo_ticket'),
        ),
    ]
