# Generated by Django 6.0.1 on 2026-01-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_vehiculo_patente_vehiculo_patente_ult3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ticket',
            field=models.CharField(max_length=20),
        ),
    ]
