# Generated by Django 6.0 on 2026-02-01 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_vehiculo_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CocheraEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='configcapacidad',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='configcapacidad',
            constraint=models.UniqueConstraint(fields=('cochera', 'tipo'), name='uq_capacidad_cochera_tipo'),
        ),
        migrations.AddField(
            model_name='cocheraempleado',
            name='cochera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.cochera'),
        ),
        migrations.AddField(
            model_name='cocheraempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cochera',
            name='empleados',
            field=models.ManyToManyField(blank=True, related_name='cocheras_asignadas', through='parking.CocheraEmpleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cocheraempleado',
            constraint=models.UniqueConstraint(fields=('cochera', 'empleado'), name='uq_cochera_empleado'),
        ),
    ]
