# Generated by Django 6.0 on 2026-02-03 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_cocheraempleado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADA', 'ACEPTADA'), ('CANCELADA', 'CANCELADA')], default='PENDIENTE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_aceptadas', to=settings.AUTH_USER_MODEL)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='parking.cochera')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cochera', 'email'), name='uq_invite_cochera_email')],
            },
        ),
        migrations.CreateModel(
            name='TarifaHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='parking.cochera')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.tipoespacio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cochera', 'tipo'), name='uq_tarifa_cochera_tipo')],
            },
        ),
    ]
