# Generated by Django 6.0.1 on 2026-02-11 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_invitacionempleado_tarifahora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='egreso_estimado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='horas_previstas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='monto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tarifa_hora_aplicada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['egreso_estimado_at'], name='parking_mov_egreso__7fd554_idx'),
        ),
    ]
