# Generated by Django 6.0.6 on 2026-06-28 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_movimiento_egreso_estimado_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrega_estimada_at', models.DateTimeField(blank=True, null=True)),
                ('entregado_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='parking.cliente')),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='parking.cochera')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='parking.vehiculo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('categoria', models.CharField(choices=[('LAVADO', 'Lavado'), ('PROTECCION', 'Protección'), ('RESTAURACION', 'Restauración'), ('DETAILING', 'Detailing / Estética'), ('OTRO', 'Otro')], default='LAVADO', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='parking.cochera')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='servicios',
            field=models.ManyToManyField(related_name='ordenes', through='parking.OrdenServicio', to='parking.servicio'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.servicio'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_ESPERA', 'En espera'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('AUSENTE', 'Ausente')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='parking.cliente')),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='parking.cochera')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno', to='parking.ordentrabajo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='parking.vehiculo')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['cochera', 'estado'], name='parking_ord_cochera_e7c38a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['cochera', 'created_at'], name='parking_ord_cochera_b0b299_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['cochera', 'fecha'], name='parking_tur_cochera_05377b_idx'),
        ),
    ]
