# Generated by Django 6.0.6 on 2026-06-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_inventario_membresia_checklist_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='parking.membresia'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='monto_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_pago',
            field=models.CharField(choices=[('HORA', 'Por hora'), ('MEMBRESIA', 'Membresía')], default='HORA', max_length=10),
        ),
    ]
