# Generated by Django 6.0.1 on 2026-02-01 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dueno_asignado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('dueno', models.F('empleado')), _negated=True), name='ck_empleado_no_es_su_propio_dueno')],
            },
        ),
    ]
